import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Lato } from 'next/font/google'
import './globals.css'
import { APP_NAME, APP_SLOGAN } from '@/lib/constants'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const lato = Lato({
//   variable: '--font-lato',
//   subsets: ['latin'],
//   weight: ['400', '700'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: {
    template: `%s | ${APP_NAME}`,
    default: `${APP_NAME}.${APP_SLOGAN}`,
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}
